Repository hassio-addons/repository-updater, pull requests merged in 2021-04, with the labels that each got.

#17 Add apparmor.txt support
  repositoryupdater/addon.py
Labels: enhancement, new-feature

#18 Fix Docker builds
  action/Dockerfile
  docker/Dockerfile
Labels: bugfix

#19 Add support for en translation file
  repositoryupdater/addon.py
Labels: new-feature
